In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels as sm



/Users/arnonmoscona/envs/3.6.1-personal/lib/python3.6/site-packages/matplotlib/font_manager.py:279: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '


In [71]:
data = np.random.randn(2,3)
np.abs(np.round(data*10))
np.array([[0,1],[1,0]])
unit = np.diag(np.ones(3))
#np.linalg.inv(data)
sq_data = np.pad(data, ((0,1), (0,0)), mode='constant')

data = np.transpose(sq_data)
inv_sq = np.linalg.pinv(sq_data)


data2 = np.random.randn(3,2)
inv2 = np.linalg.pinv(data2) # pseudo inverse (for over-determined systems like learning)
np.dot(inv2, data2) # verify

def t(matrix):
    return np.transpose(matrix)

data, t(t(data)[:2]), data[:,:2]

(array([[-0.04105392,  0.20419207,  0.        ],
        [-0.26196127, -1.77217176,  0.        ],
        [ 0.99612465, -1.11770972,  0.        ]]),
 array([[-0.04105392,  0.20419207],
        [-0.26196127, -1.77217176],
        [ 0.99612465, -1.11770972]]),
 array([[-0.04105392,  0.20419207],
        [-0.26196127, -1.77217176],
        [ 0.99612465, -1.11770972]]))